### PR TITLE
updated function names for profile processing

### PR DESCRIPTION
**Pull request by mthielma**
Some of the function names of hte function used for profile processing did not adhere to the julia standard. This PR should fix that.

### CODE REVIEW

**Review by aelligp — APPROVED** [review]

**Comment by mthielma** [comment]
The failing tests are related to a failed download of data from ISC. This often happens if there are multiple requests, as their bandwidth is quite limited. To solve this, we could add the XML file we usually download to the repository. Or we just ignore the error for the time being.

**Comment by boriskaus** [comment]
So I was unsure about this, as `ProfileData` is a Julia structure which can/should have camel names

**Comment by albert-de-montserrat** [comment]
Adding the XML is probably a bad idea, as the size of the repo will increase with every PR.... How large is this downloaded file? could the test be done with a much smaller one?

**Comment by boriskaus** [comment]
> The failing tests are related to a failed download of data from ISC. This often happens if there are multiple requests, as their bandwidth is quite limited. To solve this, we could add the XML file we usually download to the repository. Or we just ignore the error for the time being.

or you rerun the failing tests

**Comment by mthielma** [comment]
> So I was unsure about this, as `ProfileData` is a Julia structure which can/should have camel names, so I thought that `extract_ProfileData` is acceptable in that case

That is also a good point.

**Comment by mthielma** [comment]
> Adding the XML is probably a bad idea, as the size of the repo will increase with every PR.... How large is this downloaded file? could the test be done with a much smaller one?

As the download instructions are quite restrictive in space, time and magnitude, only the information of a single earthquake is downloaded, which amounts to a file size of 3 KB. I guess we could live with that. And then we don't spam the ISC with repeating downloads...

**Comment by mthielma** [comment]
I'd suggest to keep `extract_ProfileData` as a function name, but to change the others.

**Comment by albert-de-montserrat** [comment]
> > Adding the XML is probably a bad idea, as the size of the repo will increase with every PR.... How large is this downloaded file? could the test be done with a much smaller one?
> 
> As the download instructions are quite restrictive in space, time and magnitude, only the information of a single earthquake is downloaded, which amounts to a file size of 3 KB. I guess we could live with that. And then we don't spam the ISC with repeating downloads...

I guess 3Kb is acceptable :)

**Comment by mthielma** [comment]
As the last test has now repeatedly failed due to download issues, I'd just merge it.

**Pull request merged**
