### PR TITLE
Kilometer-scale volcano tutorial

### PR DESCRIPTION
**Pull request by LucaDeSiena**
This branch:

* Represents geophysical and geological data provided by local observatories and academics at the local scale. Models are in UTM.
* Shows how to represent time-dependent seismicity within existing volcanic models.
* Maybe too long, could be splitted.

### CODE REVIEW

**Comment by LucaDeSiena** [comment]
test failed for added comma in make.jl

**Comment by LucaDeSiena** [comment]
Closing pull and revising

**Comment by LucaDeSiena** [comment]
Re-test compatibility of the branch

**Comment by boriskaus** [comment]
Note that you do not need to close a PR if you spot a mistake; simply push an update to your branch and it will automatically rerun the tests

**Comment by boriskaus** [comment]
In addition, please note that we (just) added the `UTMData` structure, which allows directly importing data with `UTM` coordinates (and convert it to `GeoData` for visualization). 
See the [tutorial](https://juliageodynamics.github.io/GeophysicalModelGenerator.jl/dev/man/tutorial_UTM/) as well. 
It would be good if you can utilise that in your tutorial as well (you may have to push the latest update of `main` back into your branch).

**Comment by LucaDeSiena** [comment]
Ok, will work on adapting the tutorial

**Comment by boriskaus** [comment]
Thanks, this will be a great tutorial. Some comments:

1. The code under step 4 does not work as given, as it is called `depth` instead of `depthUTM`, so change the line 
```julia
julia> depth =   data[:,3];
```
to 
```julia
julia> depthUTM =   data[:,3];
```

2. Isn't the data you read from the file `modvPS.dat` given in UTM coordinates? If so, I don't understand the line
```julia
julia> Data_set_Cartesian  =   CartData(we, sn, depth, (vp = Vp3d * (km / s), vs = Vs3d * (km / s), vpvs = Vp_Vs3d,))
```
I think it is clearer if you read it in as `UTM`:
```julia
julia> Data_set_UTM  =   UTMData(we, sn, depth, 33, true, (vp = Vp3d * (km / s), vs = Vs3d * (km / s), vpvs = Vp_Vs3d,))
```
In case you want to convert this to Cartesian data (that has the coordinate axis in km's, which is what we use in LaMEM), you need to define a `ProjectionPoint` around which the Cartesian data will be centered. A `ProjectionPoint` can be defined with `Lat/Lon` coordinates, or (in your case easier) with UTM data, in which case we also need to specify the zone & whether we are on the northern hemisphere 
```julia
julia> proj = ProjectionPoint(mean(Data_set_UTM.EW.val),mean(Data_set_UTM.NS.val),33,true)
ProjectionPoint(40.81783289893781, 14.144736955784808, 427873.0, 4.518887e6, 33, true)
```
Next, you can convert this to `CartData` using
```julia
julia> Convert2CartData(Data_set_UTM,proj)
CartData 
    size : (116, 96, 7)
    x    ϵ [ -5.75 km : 5.75 km]
    y    ϵ [ -4.75 km : 4.75 km]
    z    ϵ [ -4.2 km : 0.6 km]
    fields : (:vp, :vs, :vpvs)
```
3. In section 5, `julia>   name_vts        = name[24:26];` should be `julia>   name_vts        = nameFile[24:26];`
4. You can combine various statements within a single `findall` statement using:
```julia
ind           = findall( (WE .>= 419000) .& (WE.<=435000) .& (SN.>=4514000) .& (SN.<=4528000) );
```
5. Do I understand it correctly that you are plotting time-dependent tomographic data? If so, it would be great if you could simply push the `play` button in Paraview and visualise that. Internally, we are using the great [writeVTK](https://github.com/jipolanco/WriteVTK.jl) package to write paraview data, and this has the option to write `.pvd` files. It would be fantastic if we can use that here as well (and write a `*.pvd` file). To be tested

**Comment by LucaDeSiena** [comment]
> 1. The code under step 4 does not work as given, as it is called `depth` instead of `depthUTM`, so change the line
 **Corrected**

>  1. Isn't the data you read from the file `modvPS.dat` given in UTM coordinates? If so, I don't understand the line
> 
> ```julia
> julia> Data_set_Cartesian  =   CartData(we, sn, depth, (vp = Vp3d * (km / s), vs = Vs3d * (km / s), vpvs = Vp_Vs3d,))
> ```

I am unable to read the shape files containing coastline and morphology using the UTM routines. These shape files are readable in Julia via Shape [Shapefile.jl](https://github.com/JuliaGeo/Shapefile.jl/blob/master/README.md), but there is no way to save them. I have tried using ArchGDAL.jl and GDAL.jl with no success. See the discussion [here](https://discourse.julialang.org/t/how-to-create-a-new-shapefile-containing-a-few-points/43454). Together with UTMdata I also use CartData, so that I can read them in a simple XYZ environment - ProjectionPoint does not solve my issue as the shape files are in UTM. MY Paraview is broken at present, so I cannot recreate the figures. But I agree that a tutorial with ProjectPoint would be useful.


>  1. In section 5, `julia>   name_vts        = name[24:26];` should be `julia>   name_vts        = nameFile[24:26];`

**Corrected**
> 2. You can combine various statements within a single `findall` statement using:

**Done**

>  1. Do I understand it correctly that you are plotting time-dependent tomographic data? If so, it would be great if you could simply push the `play` button in Paraview and visualise that. Internally, we are using the great [writeVTK](https://github.com/jipolanco/WriteVTK.jl) package to write paraview data, and this has the option to write `.pvd` files. It would be fantastic if we can use that here as well (and write a `*.pvd` file). To be tested

No, I plot seismicity with time - this allows me to reproduce the results of [this paper](https://www.nature.com/articles/s41598-017-08192-7?iu=&iap=false&exception=true&cust_params=). I will try creating a movie where. earthquakes evolve through time as soon as the branch passes the tests and is merged.

**Comment by boriskaus** [comment]
all right, fair enough. Thanks for your contribution!

**Review by boriskaus — APPROVED** [review]

**Pull request merged**
