### PR TITLE
Import Gmsh meshes

### PR DESCRIPTION
**Pull request by boriskaus**
This imports a Gmsh mesh with:
Screenshot 2024-03-29 at 19 49 43

```Julia
julia> fname="test_files/subduction_ptatin.msh"
julia> fe_data, tag_names = import_Gmsh(fname);
julia> fe_data
FEData{3,4} 
    elements : 127
    vertices : 49
     x       ϵ [ 0.0 : 1.0e6]
     y       ϵ [ -300000.0 : 0.0]
     z       ϵ [ 0.0 : 600000.0]
      fields : 
  cellfields : (:regions,)
```

And allows setting the regions on the `CartData` mesh:

```Julia
julia> bbox = extrema(fe_data_gmg);
julia> nx,ny,nz = 100,50,80
julia> data_cart = CartData( xyz_grid(range(bbox[1]...,length=nx),range(bbox[2]...,length=ny),range(bbox[3]...,length=nz) ))
julia> data_cart1 = project_FEData_CartData(data_cart, data_fe)
```
Screenshot 2024-03-29 at 19 50 24

### CODE REVIEW

**Review by NicolasRiel — COMMENTED** [review]
It seems I have a problem when trying to use:

```Julia
julia> fname="test_files/subduction_ptatin.msh"
"test_files/subduction_ptatin.msh"
julia> fe_data, tag_names = import_Gmsh(fname);
ERROR: MethodError: no method matching import_Gmsh(::String)

julia> fe_data, tag_names = GeophysicalModelGenerator.import_Gmsh(fname);
ERROR: MethodError: no method matching import_Gmsh(::String)
Stacktrace:
 [1] top-level scope
   @ REPL[13]:1
```

Am I doing something wrong?

**Review by aelligp — APPROVED** [review]

**Comment by NicolasRiel** [comment]
Is it working for you @aelligp ?

**Comment by boriskaus** [comment]
Did you load GridapGmsh along with GMG? That is required for this function to become available

**Comment by NicolasRiel** [comment]
Oh ok will try a bit later

**Review by NicolasRiel — APPROVED** [review]
Works for me!
image

**Pull request merged**
