### PR TITLE
ProfileProcessing rewrite & fixes

### PR DESCRIPTION
**Pull request by boriskaus**
This reorganises the ProfileProcessing functions such that we split reading the data (which can be time consuming if downloading online data) from processing cross-sections.
It also adds tests.

The general functionality is:
1. Read dataset definitions from file:
```Julia
julia> Datasets = Load_Dataset_file("test_files/AlpineData.txt"); 
```
2. Load the actual data
```julia
julia> DataVol, DataSurf, DataPoint, DataScreenshot, DataTopo = load_GMG(Datasets); # read active data
```
3. Define a profile:
```julia
julia> profile = ProfileData(start_lonlat=(5,45), end_lonlat=(15,49)). #define profile
Vertical ProfileData
  lon/lat    : (5.0, 45.0)-(15.0, 49.0) 
```
4. Combine different volumetric data into one dataset (using the dimensions of the first dataset as reference by default; can be changed)
```julia
Julia> VolData_combined = combine_VolData(VolData). # merge volume datasets into a single one
```
5. Project all data onto the profile
```julia
julia> ExtractProfileData!(profile, VolData_combined, SurfData, PointData) 
```

For backwards compatibility with the MATLAB GUI, we also provide the function `ExtractProfileData`:
```julia
julia> ProfileCoordFile = "test_files/PickedProfiles.txt"
julia> ProfileNumber = 1
julia> DataSetFile="test_files/AlpineData_remote.txt
julia> DepthVol=nothing
julia> DimsVolCross=(100,100)
julia> Depth_extent=nothing
julia> DimsSurfCross=(100,)
julia> section_width=50km
julia> ExtractProfileData(ProfileCoordFile, ProfileNumber,DataSetFile, DimsVolCross=DimsVolCross,DepthVol=Depth_extent,DimsSurfCross=DimsSurfCross,WidthPointProfile=section_width)

```

### CODE REVIEW

**Review by mthielma — COMMENTED** [review]
Looks good to me. I would remove all the junk from the tutorial file that I started, so that we have a clean start for the tutorial.

**Review by mthielma — COMMENTED** [review]
Does ExtractProfileData! only work if VolData,SurfData and PointData are given? I would suggest to make these arguments optional, so that one can also process e.g. only volume data.

**Comment by boriskaus** [comment]
> Does ExtractProfileData! only work if VolData,SurfData and PointData are given? I would suggest to make these arguments optional, so that one can also process e.g. only volume data.

If they are give as empty NamedTuples (i.e. `NamedTuple()`) they will not be processed.

**Review by mthielma — APPROVED** [review]
Good to go!

**Pull request merged**
