### PR TITLE
Rework `InterpolateTopographyOnPlane` as a `InterpolateDataFields2D` method 

### PR DESCRIPTION
**Pull request by albert-de-montserrat**
Example 
```julia
# should throw an error with a 2D dataset
Lon,Lat,Depth   =   LonLatDepthGrid(10:20,30:40,-50km);
Data1           =   Depth*2;                # some data
Vx1,Vy1,Vz1     =   Data1*3,Data1*4,Data1*5
Data_set2D      =   GeoData(Lon,Lat,Depth,(Depthdata=Data1,LonData1=Lon, Velocity=(Vx1,Vy1,Vz1)))  
@test_throws ErrorException CrossSection(Data_set2D, Depth_level=-10)

# Test interpolation of depth to a given cartesian XY-plane
x = 11:19
y = 31:39
plane1 = InterpolateDataFields2D(Data_set2D, x, y)
proj   = ProjectionPoint()
plane2 = InterpolateDataFields2D(Data_set2D, proj, x, y)

@assert plane1 == plane2
@assert all(==(-50e0), plane1)
```

### CODE REVIEW

**Comment by albert-de-montserrat** [comment]
I'll fix the errors before merging. But CI is working.

**Comment by mthielma** [comment]
Looks good to me.

**Review by mthielma — APPROVED** [review]

**Comment by mthielma** [comment]
From the failing tests, it seems that it is still looking for InterpolateTopographyOnPlane somewhere. Maybe it is still being exported?

**Comment by albert-de-montserrat** [comment]
Yep that's fixed now. 1.9 in Ubuntu fails because of an unrelated GMT issue in downloading something.

**Pull request merged**
