### PR TITLE
Cross section surface

### PR DESCRIPTION
**Pull request by mthielma**
This pull request adds the possibility to create profiles not only from volume data, but also from surface data (e.g. Moho geometry) and point data (e.g. earthquake data). Creating the different profiles is still done via the CrossSection function, but the behaviour now differs whether volume, surface or point data is given.

### CODE REVIEW

**Comment by boriskaus** [comment]
so this is failing because of `linear_interpolation`. Shall we simply update this to the latest version of `Interpolations.jl`?
Does this also imply that we have to increase the minimum Julia version?

**Review by boriskaus — CHANGES_REQUESTED** [review]
Looks good to me, but why is the `.DS_Store` binary file added here? 
Also, before committing the test suite should work fine. And you may increment the version of GMG

**Comment by mthielma** [comment]
As far as I understand, LinearInterpolation is deprecated in newer versions of Interpolations.jl and linear_interpolation should be used. So I guess increasing the minimum julia version should solve that.

**Comment by boriskaus** [comment]
> As far as I understand, LinearInterpolation is deprecated in newer versions of Interpolations.jl and linear_interpolation should be used. So I guess increasing the minimum julia version should solve that.

ok, please do so (in `Project.toml`. we also need to change the CI in that case, to no longer test for Julia 1.6

**Pull request merged**
